server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          url: https://github.com/LoJoan1216/heima-config.git
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka